"""empty message

Revision ID: 005095dae6ea
Revises: 5435a530b73e
Create Date: 2024-04-19 09:49:29.392387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005095dae6ea'
down_revision = '5435a530b73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('vehicle_class', sa.String(length=250), nullable=False),
    sa.Column('length', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicules')
    # ### end Alembic commands ###
