"""empty message

Revision ID: a9fdbcd8f5c0
Revises: fb32e70dee93
Create Date: 2024-04-19 10:22:48.433932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fdbcd8f5c0'
down_revision = 'fb32e70dee93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('vehicle_class', sa.String(length=250), nullable=False),
    sa.Column('length', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vehicules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('vehicle_class', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicules_pkey')
    )
    op.drop_table('vehicles')
    # ### end Alembic commands ###
