"""empty message

Revision ID: fb32e70dee93
Revises: 190ee19de10e
Create Date: 2024-04-19 10:19:49.974158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb32e70dee93'
down_revision = '190ee19de10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('vehicle_class', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorite_character_pkey')
    )
    # ### end Alembic commands ###
